#!/bin/bash
OPTIONS="\"Hello\" \"Something asd\" \"Quit\""
select opt in $OPTIONS; do
   if [ "$opt" = "Quit" ]; then
    echo done
    IFS=${OLD_IFS}
    exit
   elif [ "$opt" = "Hello" ]; then
    echo Hello World
   else
    clear
    echo bad option
   fi
done